### ISSUE TITLE
JVM Crash

### ISSUE THREAD

**Issue by sklett-src** [Ravaelles/Atlantis#11] opened 2017-07-27 11:08 UTC
Probably unrelated to Atlantis, but did anyone else have this problem, and if not, which jre are you using?

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x6d216e8b, pid=4372, tid=0x000015e8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_141-b15) (build 1.8.0_141-b15)
# Java VM: Java HotSpot(TM) Client VM (25.141-b15 mixed mode, sharing windows-x86 )
# Problematic frame:
# V  [jvm.dll+0xd6e8b]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# G:\workspaces\workspaceSSCAI\Atlantis\hs_err_pid4372.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

```

Happens every 40 runs or so.

**Comment by dgant** [comment] 2017-08-18 17:17
@sklett-src what was in the error log?

Access violations involve an interaction with BWMirror. Some of them are caused by bugs in BWMirror itself; others are due to passing in null pointers.

If the log file doesn't shed any light on it, take a look through https://github.com/vjurenka/BWMirror/issues

**Comment by Ravaelles** [comment] 2022-01-16 10:49
Closing as new version is based on JBWAPI.

**Closed as completed by Ravaelles** 2022-01-16 10:49 UTC
